### ISSUE TITLE
Package is not available anymore on npm

### ISSUE THREAD

**Issue by the-line** [yurks/content-disposition-parser#1]
The installation instructions do not work any more because the package is not published on npm.

Is it possible to add it to the npm registry again? :)
If not, the instructions should be changed

**Comment by yurks** [comment]
published, thanks

**Comment by the-line** [comment]
Thanks for publishing the package.

This package is nicely made, especially seeing all the odd corner-cases it supports. Also good to see a great deal of tests.

**Comment by yurks** [comment]
Thanks for your rating, glad to know this tool helps you. enjoy 😊
